// Posts
export const DELETE_POST = "DELETE_POST"
export const CHANGE_SORT_ORDER = "CHANGE_SORT_ORDER"
export const ADD_POST = "ADD_POST"
export const UPDATE_POST = "UPDATE_POST"
export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST"
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS"
export const FETCH_POSTS_FAILURE = "FETCH_POSTS_FAILURE"
export const VOTE_REQUEST = "VOTE_REQUEST"
export const VOTE_SUCCESS = "VOTE_SUCCESS"
export const VOTE_FAILURE = "VOTE_FAILURE"

// Comments
export const DELETE_COMMENT = "DELETE_COMMENT"
export const RESET_COMMENTS = "RESET_COMMENTS"
export const ADD_COMMENT = "ADD_COMMENT"
export const UPDATE_COMMENT = "UPDATE_COMMENT"
export const FETCH_COMMENTS_REQUEST = "FETCH_COMMENTS_REQUEST"
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS"
export const FETCH_COMMENTS_FAILURE = "FETCH_COMMENTS_FAILURE"
export const VOTE_COMMENT_SUCCESS = "VOTE_COMMENT_SUCCESS"

// Categories
export const FETCH_CATEGORIES_REQUEST = "FETCH_CATEGORIES_REQUEST"
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS"
export const FETCH_CATEGORIES_FAILURE = "FETCH_CATEGORIES_FAILURE"